---
title: "Trabajo practico 1"
format: pdf
editor: visual
---

## The Multiarmed Bandit

Integrantes: Tomas Anderson, Alejo Vaschetti, Manuel Moresi

Profesores: Tomas Capretto, Ignacio Evangelista

Fecha de entrega: 17/04/2024

\newpage

## Introduccion

To do

# Desarrollo

## Situación ideal

La situación ideal seria conocer de antemano cual máquina es la que tiene la mayor probabilidad de ganar y jugar siempre con ella. Esta sería la mejor forma de ganar dinero, por lo que una buena estrategia tiene que asemejarse a dicha situación.

Para ver la cantidad de dinero que gana en promedio este método se simulan a 1000 personas jugando 1 año utilizándolo. Estos fueron los resultados:

/histograma/

En este modus operandi una persona que juege un año se espera que va a ganar alrededor de "201.986" unidades monetarias. En el 95% de los años simulados las ganancias totales se encontraron entre "184" y "220" unidades monetarias. Dicho intervalo, y los que seran presentados en las próximas estrategias, se encuentran entre el 2,5% y el 97,5% de las ganancias totales del método ordenadas de menor a mayor.

Para ver que tan beneficioso es cada estrategia, se comparan la cantidad de veces que se gana en promedio esperando que se acerque lo máximo posible a esta forma de jugar. Además, se contrastan los límites de los intervalos propuestos.

## Estrategia 1: Completamente al azar

Esta estrategia consiste en elegir cada día al azar qué máquina jugar, teniendo las tres la misma probabilidad de ser selectas. Esta es la estrategia mas basica, ya que no requiere ningun tipo de informacion previa ni evoluciona en el tiempo.

Se juega un año con esta estrategia y se obtienen los siguites resultados:

/3 lineas/ /1 linea/

La cantidad de veces que se juegan las 3 máquinas son similares, y la diferencia entre ellas se debe puramente al azar. Este hecho impacta en la evolución de la credibilidad sobre la probabilidad de éxito de cada máquina, como se ve a continuación.

/posterior 1/ /posterior 2/ /posterior 3/

Al jugarse una cantidad similar de veces en cada máquina la credibilidad se concentra en igual medida alrededor de los valores de las probabilidades de éxito de cada una.
Estos son "valor 1", "valor 2" y "valor 3" para la máquina 1, 2 y 3 respectivamente.



Las simulaciones de los 1000 años arrojaron los siguientes resultados:

/histograma/

En promedio, siguiendo esta estrategia, se espera ganar "158.609" unidades monetarias en un año.

El 95% de las ganancias al final del año estuvieron entre "140" y "178".

El promedio de ganancias al fianl del año es sustancialmente mas chico que el de la situacion ideal y los intervalos siquiera se superponen. Se puede pensar que esta estrategia no es recomendable al diferir tanto de un resultado ideal.



## Estrategia 2: Greedy con tasa observada

La maquina que esta estrategia selecciona en un cierto dia es aquella que tenga la mayor probabilidad de éxito observada hasta el momento. Como al empezar el año no se tiene ninguna informacion sobre la probabilidad de éxito de cada maquina, se decide jugar cada una por separado hasta todas tengan su primer éxito.

Se juega un año con esta estrategia y se obtienen los siguites resultados:

/3 lineas/  /1 linea/

En este año se usa casi exclusivamente la maquina "x" y apenas se utilizan las otras dos. Esto pasa porque las probabilidades de exitos iniciales observadas son muy variables, por lo que la primera maquina en tener varios fracasos va a tener una probabilidad muy chica y se dejara de usar. Esto impacta a la credibilidad sobre la probabilidad de éxito de cada máquina de la siguiente manera.


/posterior 1/ /posterior 2/ /posterior 3/

La credibilidad sobre la probabilidad de exito de la maquina "x" va a ser muy precisa, al tener muchas muestras de ella, y las demas seran poco precisas y muy parecidas a nuestra creencia inical.

Las simulaciones de los 1000 años arrojaron los siguientes resultados:


/tabla/ promedio de cant de veces que se usa cada maquina

/histograma/


En promedio, siguiendo esta estrategia, se espera ganar "valor" unidades monetarias en un año.

El 95% de las ganancias al final del año estuvieron entre "valor" y "valor".

Si bien es un metodo que puede generar mucha ganancia, al usar la mejor maquina mayoritariamente, es arriesgado porque hay una probabilidad de usar por el año entero la peor maquina posible.

